# Generated by Django 6.0.6 on 2026-06-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='Email Address'),
            preserve_default=False,
        ),
    ]
