# Generated by Django 6.0.6 on 2026-06-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_playerprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Address'),
        ),
    ]
