# Generated by Django 6.0.6 on 2026-06-06 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('size', models.IntegerField(default=5, verbose_name='Board Size')),
                ('difficulty', models.CharField(default='normal', max_length=255, verbose_name='Difficulty Level')),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Puzzle ID')),
                ('puzzle_data', models.JSONField(verbose_name='Puzzle Data')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('time_taken', models.DurationField(blank=True, null=True, verbose_name='Time Taken')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.puzzle', verbose_name='Puzzle')),
            ],
        ),
    ]
