# Generated by Django 6.0.6 on 2026-06-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Session ID'),
        ),
    ]
