# Generated by Django 6.0.6 on 2026-06-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_gamesession_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='solution_data',
            field=models.JSONField(default='', verbose_name='Solution Data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='size',
            field=models.IntegerField(default=5, verbose_name='Size'),
        ),
    ]
