# Generated by Django 6.0.6 on 2026-06-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_puzzle_solution_data_alter_puzzle_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='solution_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Solution Data'),
        ),
    ]
